url: https://danielsaad.com
baseurl: /blog
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - github-pages
title: "Blog"
description: ""
author: danielsaad
instagram:


# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      mathjax: true